import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const server = spawn('npx', ['vite', 'preview', '--port', '4175', '--strictPort'], { stdio: 'pipe' });
await new Promise(r => setTimeout(r, 2500));
const browser = await chromium.launch({ headless: true, executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1000, height: 620 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:4175/');
await page.waitForTimeout(1500);
await page.screenshot({ path: 'test/shots/menu.png' });
await page.click('#btn-deck'); await page.waitForTimeout(300);
await page.screenshot({ path: 'test/shots/deck.png' });
await page.click('#btn-deck-back'); await page.click('#btn-play'); await page.waitForTimeout(1000);
// joga uma carta manualmente: seleciona carta 1 e clica na lane do meio
await page.evaluate(() => { game.player.capital = 10; });
await page.click('#hand .card:nth-child(1)'); await page.waitForTimeout(300);
await page.screenshot({ path: 'test/shots/select.png' });
await page.mouse.click(500, 380); await page.waitForTimeout(1500);
const st = await page.evaluate(() => ({ units: game.units.count, cap: game.player.capital, sel: game.player.selected }));
console.log('after manual play:', JSON.stringify(st));
await page.screenshot({ path: 'test/shots/played.png' });
await page.evaluate(() => game.finish(true)); await page.waitForFunction(() => !document.getElementById('end-screen').classList.contains('hidden'), null, { timeout: 60000 }); await page.waitForTimeout(500);
await page.screenshot({ path: 'test/shots/victory.png' });
const endVisible = await page.evaluate(() => !document.getElementById('end-screen').classList.contains('hidden'));
console.log('end screen visible:', endVisible);
await page.click('#btn-restart'); await page.waitForTimeout(1000);
const st2 = await page.evaluate(() => ({ playing: game.playing, php: game.bases.player.hp, bhp: game.bases.bot.hp, units: game.units.count }));
console.log('after restart:', JSON.stringify(st2));
await page.evaluate(() => game.finish(false)); await page.waitForFunction(() => !document.getElementById('end-screen').classList.contains('hidden'), null, { timeout: 60000 }); await page.waitForTimeout(500);
await page.screenshot({ path: 'test/shots/defeat.png' });
console.log('errors:', errors.length ? errors.join('\n') : 'none');
await browser.close(); server.kill(); process.exit(0);
